encrypt-type: # 0:standard, 1:guomi
    encrypt-type: 0

group-channel-connections-config:
    caCert: classpath:ca.crt
    sslCert: classpath:sdk.crt
    sslKey: classpath:sdk.key
    all-channel-connections:
        -   group-id: 1 #group ID
            connections-str:
                - 127.0.0.1:20200 # node listen_ip:channel_listen_port
                - 127.0.0.1:20201

channel-service:
    group-id: 1 # The specified group to which the SDK connects
    agency-name: fisco # agency name

accounts:
    pem-file: 0x55f934bcbe1e9aef8337f5551142a442fdde781c.pem
    p12-file: 0x98333491efac02f8ce109b0c499074d47e7779a6.p12
    password: 123456
